CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE DATABASE auth_db;
-- connect: \c auth_db
CREATE TABLE users (user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), username VARCHAR(100) UNIQUE NOT NULL, password_hash TEXT NOT NULL, role VARCHAR(30) NOT NULL CHECK(role IN ('ADMIN','USER')), is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
